BACKEND_DIR := $(shell pwd)/backend

all: test
	@echo "backend tests complete...""

test:
	@echo "backend tests starting..."
	dotnet test Concierge.Api.Tests/Concierge.Api.Tests.csproj
	@echo "backend tests complete..."
