services:
  backend:
    build:
      context: ..  # Assuming your project root is the parent directory
      dockerfile: deployment/Dockerfile.backend
    # Map host port to container port    
    ports:
      - "${BACKEND_HOST_PORT}:80"   
    environment:
      - ASPNETCORE_URLS=http://+:80
  # TODO: Add other services like database, frontend, etc.

# TODO: Define any necessary networks or volumes
# networks:
#   app_network:
#     driver: bridge
#
# volumes:
#   db_data: 