services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    ports:
      # Use an environment variable for the host port, mapping to container port 80
      - "${BACKEND_HOST_PORT}:80"
    environment:
      # Container always listens on port 80 internally
      - ASPNETCORE_URLS=http://+:80

  # TODO: Add other services like database, frontend, etc.

# TODO: Define any necessary networks or volumes
# networks:
#   app_network:
#     driver: bridge
#
# volumes:
#   db_data: 